name: GitHub Actions Demo
# on:
#   schedule:
#   - cron: '0 12 * * 1'
on: [push,pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          curl -X GET "https://api.github.com/repos/Hemabai/Git-practise/pulls?updated_at:2022-06-17..2022-06-24&&state=all" \
          | grep "html_url" | grep "/pull/" >> pullreqs.txt
      - run: cat pullreqs.txt
      - run: echo "This job's status is ${{ job.status }}."
      
      # Send email to recipients
      - name: Send email
      # You may pin to the exact commit or the version.
      # uses: dawidd6/action-send-mail@6d23605227c578d570e5594931720f85a1af55a2
        uses: dawidd6/action-send-mail@v3.6.1
         with:
      # SMTP server address
            server_address: 
      # SMTP server port
            server_port: 
      # Authenticate as this user to SMTP server
            username: # optional
      # Authenticate with this password to SMTP server
            password: # optional
      # Subject of mail message
            subject: 
      # Recipients mail addresses (separated with comma)
            to: 
      # Full name of mail sender (might be with an email address specified in <>)
    from: 
    # Whether this connection use TLS (default is true if server_port is 465)
    secure: # optional
    # Body of mail message (might be a filename prefixed with file:// to read from)
    body: # optional
    # HTML body of mail message (might be a filename prefixed with file:// to read from)
    html_body: # optional
    # Carbon copy recipients (separated with comma)
    cc: # optional
    # Blind carbon copy recipients (separated with comma)
    bcc: # optional
    # An email address that will appear on the Reply-To field
    reply_to: # optional
    # The Message-ID this message is replying to
    in_reply_to: # optional
    # Allow unsigned/invalid certificates
    ignore_cert: # optional
    # Convert body from Markdown to HTML (set content_type input as text/html too)
    convert_markdown: # optional
    # Files that will be added to mail message attachments (separated with comma)
    attachments: # optional
    # Set Priority level for the mail message to 'high', 'normal' (default) or 'low'
    priority: # optional
      
