name: GitHub Actions Demo

# on:
#   schedule:
#   - cron: '0 12 * * 1'

on: [push,pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          curl -X GET "https://api.github.com/repos/Hemabai/Git-practise/pulls?updated_at:2022-06-17..2022-06-24&&state=all" \
          | grep "html_url" | grep "/pull/" >> pullreqs.txt
      - run: cat pullreqs.txt
      - run: echo "This job's status is ${{ job.status }}."
      
     
      
